### ISSUE TITLE
Erro no Exemplo em Flutter - Sat.java - import br.com.elgin.sat.ElginSATMainActivity; ( Não Existe na Lib )

### ISSUE THREAD

**Issue by claudneysessa** [ElginDeveloperCommunity/PDV_Android_M8_M10#4]
Somente na parte e em que disponibiliza a integração com o SAT, o import não está sendo identificado:

![image](https://user-images.githubusercontent.com/12506432/137365036-bf9f13dd-c01f-40a6-ac09-8f2fa09bf81f.png)

não esta disponível na lib

![image](https://user-images.githubusercontent.com/12506432/137365121-145c0874-cbf4-43cb-8265-2548aac7a013.png)

Comentando a parte do SAT tudo funciona 100%

**Comment by BrunoLeonVieira** [comment]
Done 👍 
check this in link: https://bitbucket.org/teamshelgin/exemplo_sat_e1_android/src/master/

**Comment by claudneysessa** [comment]
Rapaz, pode encerrar mais ainda não fiz funcionar direito, dificuldade deviso ao exemplo esta desatualizado não corresponde ao manual...
fica o feedback, pode encerrar...

**Comment by ElginDeveloperCommunity** [comment]
Oi @claudneysessa, espero que já tenha conseguido resolver esse erro de import. Caso ainda esteja com dificuldades, pode pedir ajuda no nosso [discord](https://discord.gg/2RpmUaFq9Q).
